void main() // Position - 0x0 (0)
{
	func_1();
	Global_2696914 = true;
	SCRIPT::TERMINATE_THIS_THREAD();
	return;
}

void func_1() // Position - 0x15 (21)
{
	Global_1689076[0] = joaat("MPPLY_AWD_FM_CR_RACES_MADE") /* TUNEABLE: MPPLY_AWD_FM_CR_RACES_MADE, MPPLY_AWD_FM_CR_RACES_MADE */;
	Global_1689076[1] = joaat("MPPLY_AWD_FM_CR_DM_MADE") /* TUNEABLE: MPPLY_AWD_FM_CR_DM_MADE, MPPLY_AWD_FM_CR_DM_MADE */;
	Global_1689076[2] = joaat("MPPLY_AWD_FM_CR_PLAYED_BY_PEEP") /* TUNEABLE: MPPLY_AWD_FM_CR_PLAYED_BY_PEEP, MPPLY_AWD_FM_CR_PLAYED_BY_PEEP */;
	Global_1689076[3] = joaat("MPPLY_AWD_FM_CR_MISSION_SCORE") /* TUNEABLE: MPPLY_AWD_FM_CR_MISSION_SCORE */;
	Global_1689076[4] = joaat("MPPLY_AWD_TEMPAWARD") /* TUNEABLE: MPPLY_AWD_TEMPAWARD */;
	Global_1689082[0] = joaat("MPPLY_AWD_TEMPAWARDFLOAT") /* TUNEABLE: MPPLY_AWD_TEMPAWARDFLOAT */;
	Global_1689084[0] = joaat("MPPLY_AWD_TEMPAWARDBOOL") /* TUNEABLE: MPPLY_AWD_TEMPAWARDBOOL */;
	Global_1689084[1] = joaat("MPPLY_AWD_GANGOPS_IAA") /* TUNEABLE: MPPLY_AWD_GANGOPS_IAA */;
	Global_1689084[2] = joaat("MPPLY_AWD_GANGOPS_SUBMARINE") /* TUNEABLE: MPPLY_AWD_GANGOPS_SUBMARINE */;
	Global_1689084[3] = joaat("MPPLY_AWD_GANGOPS_ALLINORDER") /* TUNEABLE: MPPLY_AWD_GANGOPS_ALLINORDER */;
	Global_1689084[4] = joaat("MPPLY_AWD_GANGOPS_LOYALTY") /* TUNEABLE: MPPLY_AWD_GANGOPS_LOYALTY */;
	Global_1689084[5] = joaat("MPPLY_AWD_GANGOPS_CRIMMASMD") /* TUNEABLE: MPPLY_AWD_GANGOPS_CRIMMASMD */;
	Global_1689084[6] = joaat("MPPLY_AWD_GANGOPS_MISSILE") /* TUNEABLE: MPPLY_AWD_GANGOPS_MISSILE */;
	Global_1689084[7] = joaat("MPPLY_AWD_GANGOPS_LOYALTY2") /* TUNEABLE: MPPLY_AWD_GANGOPS_LOYALTY2 */;
	Global_1689084[8] = joaat("MPPLY_AWD_GANGOPS_LOYALTY3") /* TUNEABLE: MPPLY_AWD_GANGOPS_LOYALTY3 */;
	Global_1689084[9] = joaat("MPPLY_AWD_GANGOPS_CRIMMASMD2") /* TUNEABLE: MPPLY_AWD_GANGOPS_CRIMMASMD2 */;
	Global_1689084[10] = joaat("MPPLY_AWD_GANGOPS_CRIMMASMD3") /* TUNEABLE: MPPLY_AWD_GANGOPS_CRIMMASMD3 */;
	Global_1689084[11] = joaat("MPPLY_AWD_GANGOPS_SUPPORT") /* TUNEABLE: MPPLY_AWD_GANGOPS_SUPPORT */;
	Global_1689084[12] = joaat("MPPLY_AWD_FLEECA_FIN");
	Global_1689084[13] = joaat("MPPLY_AWD_PRISON_FIN");
	Global_1689084[14] = joaat("MPPLY_AWD_HUMANE_FIN");
	Global_1689084[15] = joaat("MPPLY_AWD_SERIESA_FIN");
	Global_1689084[16] = joaat("MPPLY_AWD_PACIFIC_FIN");
	Global_1689084[17] = joaat("MPPLY_AWD_HST_ORDER");
	Global_1689084[18] = joaat("MPPLY_AWD_HST_SAME_TEAM");
	Global_1689084[19] = joaat("MPPLY_AWD_HST_ULT_CHAL");
	Global_1689084[20] = joaat("MPPLY_AWD_COMPLET_HEIST_1STPER");
	Global_1689084[21] = joaat("MPPLY_AWD_COMPLET_HEIST_MEM");
	Global_1689107[0] = joaat("MPPLY_AWD_TEMPAWARDDATE") /* TUNEABLE: MPPLY_AWD_TEMPAWARDDATE */;
	return;
}

